#!/bin/bash
QDBUS=/usr/bin/qdbus

title=`$QDBUS --session org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep xesam:title: | sed 's/xesam:title: //'`
artist=`$QDBUS --session org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Metadata | grep xesam:artist: | sed 's/xesam:artist: //'`
echo $title - $artist

